In [16]:
import json
from pathlib import Path

import pandas as pd

In [17]:
DATA_PATH = Path("../data/raw/adzuna_jobs.json")

with open(DATA_PATH, "r", encoding="utf-8") as f:
    jobs = json.load(f)
print(f"Number of jobs: {len(jobs)}")
print(f"Type of object: {type(jobs)}")

Number of jobs: 1135
Type of object: <class 'list'>

In [18]:
#Inspect the first job posting
sample_job = jobs[0]

print(f"Type: {type(sample_job)}")
print(f"Number of keys: {len(sample_job)}")
print(f"\nKeys available:")
for key in sample_job.keys():
    print(f"- {key}")

Type: <class 'dict'>
Number of keys: 17

Keys available:
- company
- salary_max
- latitude
- category
- location
- __CLASS__
- salary_is_predicted
- redirect_url
- title
- adref
- created
- salary_min
- id
- description
- longitude
- contract_time
- _search_query

In [19]:
print(json.dumps(sample_job, indent=2, ensure_ascii=False))

{
  "company": {
    "__CLASS__": "Adzuna::API::Response::Company",
    "display_name": "ADF Medical Services Inc."
  },
  "salary_max": 98887,
  "latitude": 43.64837,
  "category": {
    "label": "IT Jobs",
    "tag": "it-jobs",
    "__CLASS__": "Adzuna::API::Response::Category"
  },
  "location": {
    "__CLASS__": "Adzuna::API::Response::Location",
    "display_name": "Toronto Dominion Centre, City of Toronto",
    "area": [
      "Canada",
      "Ontario",
      "Toronto",
      "City of Toronto",
      "Toronto Dominion Centre"
    ]
  },
  "__CLASS__": "Adzuna::API::Response::Job",
  "salary_is_predicted": "0",
  "redirect_url": "https://www.adzuna.ca/details/5710417259?utm_medium=api&utm_source=df320f6a",
  "title": "Data Analyst",
  "adref": "eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTcxMDQxNzI1OSIsInMiOiJOSEk0M1g1RjhSR2F6cUFqVVJlUEx3In0.HuMwDo75-1C5FOJ-NXA8WZ2utP9H5GxtOUJHAI9ZBOA",
  "created": "2026-04-25T13:42:06Z",
  "salary_min": 78777,
  "id": "5710417259",
  "description": "We're looking for a sharp, analytical Remote Data Analyst to help us turn data into actionable insights. If you love working with numbers, spotting trends, and making data meaningful — this role is for you. Role: Remote Data Analyst Department: Analytics & Business Intelligence Location: Fully Remote Type: Full-Time / Part-Time Requirements Collect, clean, and analyze large sets of patient and operational data Build reports, dashboards, and visualizations for internal teams Identify trends, pat…",
  "longitude": -79.3819,
  "contract_time": "full_time",
  "_search_query": "data analyst"
}

In [20]:
#Flattent the nested JSON data into a pandas DataFrame
df = pd.json_normalize(jobs)

print(f"Shape: {df.shape}")
print(f"Columns: ({len(df.columns)})")
for col in df.columns:
    print(f"- {col}")

Shape: (1135, 23)
Columns: (23)
- salary_max
- latitude
- __CLASS__
- salary_is_predicted
- redirect_url
- title
- adref
- created
- salary_min
- id
- description
- longitude
- contract_time
- _search_query
- company.__CLASS__
- company.display_name
- category.label
- category.tag
- category.__CLASS__
- location.__CLASS__
- location.display_name
- location.area
- contract_type

In [21]:
df.head(3)

,salary_max,latitude,__CLASS__,salary_is_predicted,redirect_url,title,adref,created,salary_min,id,...,_search_query,company.__CLASS__,company.display_name,category.label,category.tag,category.__CLASS__,location.__CLASS__,location.display_name,location.area,contract_type
0,98887.0,43.648370,Adzuna::API::Response::Job,0,https://www.adzuna.ca/details/5710417259?utm_m...,Data Analyst,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTcxMDQxNzI1OSIsI...,2026-04-25T13:42:06Z,78777.0,5710417259,...,data analyst,Adzuna::API::Response::Company,ADF Medical Services Inc.,IT Jobs,it-jobs,Adzuna::API::Response::Category,Adzuna::API::Response::Location,"Toronto Dominion Centre, City of Toronto","[Canada, Ontario, Toronto, City of Toronto, To...",NaN
1,NaN,43.706102,Adzuna::API::Response::Job,0,https://www.adzuna.ca/details/5715365580?utm_m...,Data Analyst,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiTkhJNDNYNUY4Ukdhe...,2026-05-01T01:13:21Z,NaN,5715365580,...,data analyst,Adzuna::API::Response::Company,Mercor,IT Jobs,it-jobs,Adzuna::API::Response::Category,Adzuna::API::Response::Location,"Toronto, Ontario","[Canada, Ontario, Toronto]",contract
2,140000.0,43.670710,Adzuna::API::Response::Job,0,https://www.adzuna.ca/details/5691595044?utm_m...,Data Analyst,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTY5MTU5NTA0NCIsI...,2026-04-06T18:35:43Z,110000.0,5691595044,...,data analyst,Adzuna::API::Response::Company,COSMO,IT Jobs,it-jobs,Adzuna::API::Response::Category,Adzuna::API::Response::Location,"Church and Wellesley, City of Toronto","[Canada, Ontario, Toronto, City of Toronto, Ch...",NaN

In [22]:
#show column types and non-null counts for each column
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1135 entries, 0 to 1134
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   salary_max             297 non-null    float64
 1   latitude               956 non-null    float64
 2   __CLASS__              1135 non-null   str
 3   salary_is_predicted    1135 non-null   str
 4   redirect_url           1135 non-null   str
 5   title                  1135 non-null   str
 6   adref                  1135 non-null   str
 7   created                1135 non-null   str
 8   salary_min             336 non-null    float64
 9   id                     1135 non-null   str
 10  description            1135 non-null   str
 11  longitude              956 non-null    float64
 12  contract_time          476 non-null    str
 13  _search_query          1135 non-null   str
 14  company.__CLASS__      1135 non-null   str
 15  company.display_name   1134 non-null   str
 16  category.label         1135 non-null   str
 17  category.tag           1135 non-null   str
 18  category.__CLASS__     1135 non-null   str
 19  location.__CLASS__     1135 non-null   str
 20  location.display_name  1135 non-null   str
 21  location.area          1135 non-null   object
 22  contract_type          306 non-null    str
dtypes: float64(4), object(1), str(18)
memory usage: 204.1+ KB

In [23]:
df.isnull().sum().sort_values(ascending=False)

salary_max               838
contract_type            829
salary_min               799
contract_time            659
longitude                179
latitude                 179
company.display_name       1
adref                      0
title                      0
redirect_url               0
salary_is_predicted        0
__CLASS__                  0
id                         0
description                0
created                    0
company.__CLASS__          0
_search_query              0
category.tag               0
category.label             0
category.__CLASS__         0
location.__CLASS__         0
location.display_name      0
location.area              0
dtype: int64

In [24]:
df.describe()

          salary_max    latitude     salary_min   longitude
count     297.000000  956.000000     336.000000  956.000000
mean   126648.851852   43.770915   86704.568452  -79.405403
std     54301.798630    0.441923   47752.644324    0.879821
min        35.000000   42.045985       0.000000  -82.996859
25%     93600.000000   43.706102   62000.000000  -79.402726
50%    120000.000000   43.706102   85000.000000  -79.402726
75%    152000.000000   43.706102  120000.000000  -79.402726
max    313500.000000   48.478713  228000.000000  -74.732620

In [25]:
# List of colmns we don't need for analysis
columns_to_drop = [
    "__CLASS__",
    "company.__CLASS__",
    "category.__CLASS__",
    "location.__CLASS__",
    "adref",
    "salary_is_predicted",
]
# Drop the columns
df = df.drop(columns=columns_to_drop)
print(f"New shape: {df.shape}") 
print(f"Remaining columns:{list(df.columns)}")

New shape: (1135, 17)
Remaining columns:['salary_max', 'latitude', 'redirect_url', 'title', 'created', 'salary_min', 'id', 'description', 'longitude', 'contract_time', '_search_query', 'company.display_name', 'category.label', 'category.tag', 'location.display_name', 'location.area', 'contract_type']

In [26]:
# Rename nested to cleaner names
df = df.rename(
    columns={
        "company.display_name": "company",
        "category.label": "category",
        "category.tag": "category_tag",
        "location.display_name": "location",   
        "location.area": "location_area",

    }
)
print(f"Colums after renaming:")
for col in df.columns:
    print(f"- {col}")

Colums after renaming:
- salary_max
- latitude
- redirect_url
- title
- created
- salary_min
- id
- description
- longitude
- contract_time
- _search_query
- company
- category
- category_tag
- location
- location_area
- contract_type

In [27]:
#Inspect the firs 5 location_area values to confirm the structure
for i in range(5):
    print(f"Job {i} :{df['location_area'].iloc[i]}")

Job 0 :['Canada', 'Ontario', 'Toronto', 'City of Toronto', 'Toronto Dominion Centre']
Job 1 :['Canada', 'Ontario', 'Toronto']
Job 2 :['Canada', 'Ontario', 'Toronto', 'City of Toronto', 'Church and Wellesley']
Job 3 :['Canada', 'Ontario', 'Toronto', 'City of Toronto', 'Toronto Dominion Centre']
Job 4 :['Canada', 'Ontario', 'Toronto']

In [28]:
#Extract the city (index 2 of the location_area list) 
df["city"] = df["location_area"].apply(lambda area : area[2] if len(area) > 2 else None)
#Check the result
print(df[["location_area", "city"]].head(10))

                                       location_area       city
0  [Canada, Ontario, Toronto, City of Toronto, To...    Toronto
1                         [Canada, Ontario, Toronto]    Toronto
2  [Canada, Ontario, Toronto, City of Toronto, Ch...    Toronto
3  [Canada, Ontario, Toronto, City of Toronto, To...    Toronto
4                         [Canada, Ontario, Toronto]    Toronto
5  [Canada, Ontario, Toronto, City of Toronto, Tr...    Toronto
6                         [Canada, Ontario, Toronto]    Toronto
7               [Canada, Ontario, Middlesex, London]  Middlesex
8               [Canada, Ontario, Middlesex, London]  Middlesex
9                         [Canada, Ontario, Toronto]    Toronto

In [29]:
#Count the most common cities in the dataset
df["city"].value_counts().head(15)

city
Toronto                 760
Peel region              84
Ottawa region            62
York region              55
Waterloo region          50
Durham region            20
Halton                   18
Middlesex                17
Hamilton region           8
Elgin region              8
Bruce region              6
Leeds and Grenville       5
Essex region              3
Nipissing region          2
Lennox and Addington      2
Name: count, dtype: int64

In [30]:
# Inspect the created columns to understand its format
print(f"Type of the column : {df['created'].dtype }")
print(f"\nFirst 5 values:")
print(df["created"].head())

Type of the column : str

First 5 values:
0    2026-04-25T13:42:06Z
1    2026-05-01T01:13:21Z
2    2026-04-06T18:35:43Z
3    2026-04-19T16:29:11Z
4    2026-04-26T17:25:50Z
Name: created, dtype: str

In [31]:
# Convert the data string to a real datetime type
df["created"] = pd.to_datetime(df["created"])
#Confirm the new type and inspect the values
print(f"Type of the column : {df['created'].dtype }")
print(f"\nDate range: from {df['created'].min()} to {df['created'].max()}")
print(f"Total span : {(df['created'].max() - df['created'].min())}")

Type of the column : datetime64[us, UTC]

Date range: from 2023-01-03 14:26:06+00:00 to 2026-05-01 12:39:47+00:00
Total span : 1213 days 22:13:41

In [32]:
#Add week and day of week columns for later analysis
df["week"] = df["created"].dt.to_period("W").astype(str)
df["day_of_week"] = df["created"].dt.day_name()
print(df[["created", "week", "day_of_week"]].head())

                    created                   week day_of_week
0 2026-04-25 13:42:06+00:00  2026-04-20/2026-04-26    Saturday
1 2026-05-01 01:13:21+00:00  2026-04-27/2026-05-03      Friday
2 2026-04-06 18:35:43+00:00  2026-04-06/2026-04-12      Monday
3 2026-04-19 16:29:11+00:00  2026-04-13/2026-04-19      Sunday
4 2026-04-26 17:25:50+00:00  2026-04-20/2026-04-26      Sunday

C:\Users\rebec\AppData\Local\Temp\ipykernel_2600\3036633215.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["week"] = df["created"].dt.to_period("W").astype(str)

In [33]:
#Outlier cleaning for salary
# Replace unrealistic salaries with NaN (anything below 25,000 CAD is suspicious)
SALARY_THRESHOLD = 25000

df.loc[df["salary_min"] < SALARY_THRESHOLD, "salary_min"] = None
df.loc[df["salary_max"] < SALARY_THRESHOLD, "salary_max"] = None

# Verify
print("Salary stats after cleaning:")
print(df[["salary_min", "salary_max"]].describe())

Salary stats after cleaning:
          salary_min     salary_max
count     286.000000     285.000000
mean   100472.080420  131903.094737
std     37411.946296   48859.297089
min     38400.000000   52000.000000
25%     72800.000000   95000.000000
50%     90000.000000  124800.000000
75%    124750.000000  156000.000000
max    228000.000000  313500.000000

In [38]:
# Distribution of jobs by year
print("Jobs by year:")
print(df["created"].dt.year.value_counts().sort_index())

print("\nJobs by year-month (last 12 months only):")
print(df["created"].dt.to_period("M").value_counts().sort_index().tail(12))

Jobs by year:
created
2023       2
2024      17
2025      91
2026    1025
Name: count, dtype: int64

Jobs by year-month (last 12 months only):
created
2025-06      5
2025-07      5
2025-08      7
2025-09      8
2025-10     11
2025-11     14
2025-12     25
2026-01     47
2026-02     84
2026-03    168
2026-04    709
2026-05     17
Freq: M, Name: count, dtype: int64

C:\Users\rebec\AppData\Local\Temp\ipykernel_2600\535407897.py:6: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  print(df["created"].dt.to_period("M").value_counts().sort_index().tail(12))

In [ ]:
# Flag jobs from the active market window (2026 only)
df["is_recent"] = df["created"].dt.year == 2026

# Quick check
print(f"Recent jobs (2026): {df['is_recent'].sum()}")
print(f"Older jobs: {(~df['is_recent']).sum()}")

Recent jobs (2026): 1025
Older jobs: 110

In [40]:
OUTPUT_PATH = Path("../data/processed/adzuna_jobs_cleaned.csv")
df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8")

print(f"Saved {len(df)} rows to {OUTPUT_PATH}")
print(f"File size :{OUTPUT_PATH.stat().st_size / (1024 * 1024):.1f} KB")

Saved 1135 rows to ..\data\processed\adzuna_jobs_cleaned.csv
File size :0.9 KB

In [41]:
# Diagnostic: check the DataFrame's actual content
print(f"Number of rows: {len(df)}")
print(f"Number of columns: {len(df.columns)}")
print(f"Memory usage: {df.memory_usage(deep=True).sum() / 1024:.1f} KB")
print(f"\nFirst row preview:")
print(df.iloc[0])

Number of rows: 1135
Number of columns: 21
Memory usage: 2269.5 KB

First row preview:
salary_max                                                 98887.0
latitude                                                  43.64837
redirect_url     https://www.adzuna.ca/details/5710417259?utm_m...
title                                                 Data Analyst
created                                  2026-04-25 13:42:06+00:00
salary_min                                                 78777.0
id                                                      5710417259
description      We're looking for a sharp, analytical Remote D...
longitude                                                 -79.3819
contract_time                                            full_time
_search_query                                         data analyst
company                                  ADF Medical Services Inc.
category                                                   IT Jobs
category_tag                                               it-jobs
location                  Toronto Dominion Centre, City of Toronto
location_area    [Canada, Ontario, Toronto, City of Toronto, To...
contract_type                                                  NaN
city                                                       Toronto
week                                         2026-04-20/2026-04-26
day_of_week                                               Saturday
is_recent                                                     True
Name: 0, dtype: object

In [42]:
# Re-read the CSV that was just saved to verify
import pandas as pd
from pathlib import Path

OUTPUT_PATH = Path("../data/processed/adzuna_jobs_cleaned.csv")

# Check file existence and size
print(f"File exists: {OUTPUT_PATH.exists()}")
print(f"File size: {OUTPUT_PATH.stat().st_size} bytes")
print(f"File size: {OUTPUT_PATH.stat().st_size / 1024:.2f} KB")

# Read it back and inspect
df_check = pd.read_csv(OUTPUT_PATH)
print(f"\nRows in saved file: {len(df_check)}")
print(f"Columns in saved file: {list(df_check.columns)}")
print(f"\nFirst 3 rows of saved file:")
print(df_check.head(3))

File exists: True
File size: 962888 bytes
File size: 940.32 KB

Rows in saved file: 1135
Columns in saved file: ['salary_max', 'latitude', 'redirect_url', 'title', 'created', 'salary_min', 'id', 'description', 'longitude', 'contract_time', '_search_query', 'company', 'category', 'category_tag', 'location', 'location_area', 'contract_type', 'city', 'week', 'day_of_week', 'is_recent']

First 3 rows of saved file:
   salary_max   latitude                                       redirect_url  \
0     98887.0  43.648370  https://www.adzuna.ca/details/5710417259?utm_m...
1         NaN  43.706102  https://www.adzuna.ca/details/5715365580?utm_m...
2    140000.0  43.670710  https://www.adzuna.ca/details/5691595044?utm_m...

          title                    created  salary_min          id  \
0  Data Analyst  2026-04-25 13:42:06+00:00     78777.0  5710417259
1  Data Analyst  2026-05-01 01:13:21+00:00         NaN  5715365580
2  Data Analyst  2026-04-06 18:35:43+00:00    110000.0  5691595044

                                         description  longitude contract_time  \
0  We're looking for a sharp, analytical Remote D... -79.381900     full_time
1  About the job Mercor connects elite creative a... -79.402726           NaN
2  About the Role We are seeking a Data Analyst/S... -79.385140     full_time

   ...                    company category category_tag  \
0  ...  ADF Medical Services Inc.  IT Jobs      it-jobs
1  ...                     Mercor  IT Jobs      it-jobs
2  ...                      COSMO  IT Jobs      it-jobs

                                   location  \
0  Toronto Dominion Centre, City of Toronto
1                          Toronto, Ontario
2     Church and Wellesley, City of Toronto

                                       location_area contract_type     city  \
0  ['Canada', 'Ontario', 'Toronto', 'City of Toro...           NaN  Toronto
1                   ['Canada', 'Ontario', 'Toronto']      contract  Toronto
2  ['Canada', 'Ontario', 'Toronto', 'City of Toro...           NaN  Toronto

                    week day_of_week is_recent
0  2026-04-20/2026-04-26    Saturday      True
1  2026-04-27/2026-05-03      Friday      True
2  2026-04-06/2026-04-12      Monday      True

[3 rows x 21 columns]